name: 'Codeowner Verifier'
description: 'Verifies that modified files have an owner specified in the CODEOWNERS file'
author: 'Garret Patten'

# TODO: Add branding

inputs:
  apiToken:
    description: 'Secret GitHub token used to retrieve GitHub Teams through the GitHub API'
    required: false
    default: null
  changedFiles:
    description: 'Modified files included in the PR or Push'
    required: true
    default: null
  deletedFiles:
    description: 'Moved or deleted files included in the PR or Push'
    required: true
    default: null
  ignoreList:
    description: 'Space-delimited string list of filepath patterns to ignore when evaluating ownership'
    required: false
    default: null
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true

outputs:
  timestamp:
    description: 'Codeowner Verifier timestamp'

runs:
  using: node16
  main: dist/index.js
