name: 'Codeowner Verifier'
description: 'A GitHub Action that verifies that modified files are owned by codeowners'
author: 'Garret Patten'

inputs:
  changedFiles:
    description: 'Modified files included in the PR or Push'
    required: true
    default: null
  deletedFiles:
    description: 'Moved or deleted files included in the PR or Push'
    required: true
    default: null
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true

outputs:
  timestamp:
    description: 'Codeowner Verifier timestamp'

runs:
  using: node20
  main: dist/index.js
