name: 'Codeowners Validator'
description: 'Validates Codeowners file'
author: 'Garret Patten'

# TODO: Add branding

inputs:
  apiToken:
    description: 'Secret GitHub token used to retrieve GitHub Teams through the API'
    required: false
    default: null
  changedFiles:
    description: 'Updated files included in the PR or Push'
    required: true
    default: null
  ignoreList:
     description: 'Space delimited string list of filepath patterns to ignore when evaluating ownership'
     required: false
     default: null
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true

outputs:
  timestamp:
    description: 'Codeowners Validator timestamp'

runs:
  using: 'node12'
  main: 'dist/index.js'