name: 'Codeowners Validator'
description: 'Validates Codeowners file'
author: 'Garret Patten'

# TODO: Add branding

inputs:
  codeownersPath:
    description: 'The Codeowners path'
    required: true
    default: '.github/CODEOWNERS'
  changedFiles:
    description: 'Updated files included in the PR or Push'
    required: true;
    default: null
  GITHUB_TOKEN:
    description: 'GitHub Token'
    required: true

outputs:
  timestamp:
    description: 'Codeowners Validator timestamp'

# TODO: Update to run minified dist/index.js
runs:
  using: 'node12'
  main: 'src/action.js'