name: Build

on:
  pull_request:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - name: Update dependencies
        run: npm i

      - name: Run Build
        run: npm run build

      - name: Commit Changes
        run: |
          git config --global user.name 'Garret Patten'
          git config --global user.email 'garretpatten@users.noreply.github.com'
          git commit -m "chore: Run Build"
          git push origin main

