name: 'codeowner-verifier'

on: pull_request

jobs:
  codeowner-verifier:
    runs-on: ubuntu-latest
      - name: Identify Changed Files
        id: diff
        run: |
          git_diff="$(git diff --name-only origin/$GITHUB_BASE_REF $GITHUB_SHA)"
          git_diff_fixed="$(echo $git_diff | tr '\n' ' ' )"
          echo "git_diff=$git_diff_fixed" >> $GITHUB_OUTPUT

      - name: Identify Deleted Files
        id: deleted
        run: |
          git_diff_deleted="$(git diff --name-only --diff-filter=D origin/$GITHUB_BASE_REF $GITHUB_SHA)"
          git_diff_deleted_fixed="$(echo $git_diff_deleted | tr '\n' ' ' )"
          echo "git_diff_deleted=$git_diff_deleted_fixed" >> $GITHUB_OUTPUT

      - name: Codeowner Verifier
        id: codeowner-verifier
        uses: garretpatten/codeowner-verifier@main
        with:
          changedFiles: ${{ steps.diff.outputs.all }}
          deletedFiles: ${{ steps.deleted.outputs.git_diff_deleted }}
          ignoreList: '.git/ .vscode/ node_modules/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Finish and Output Time
        run: |
          echo "Codeowner Verifer has completed."
          echo "Time: ${{ steps.codeowner-verifier.outputs.timestamp }}"
