name: 'Codeowner Verifier Workflow'

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  codeowner-verifier-workflow:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Identify Changed Files
        id: diff
        uses: jitterbit/get-changed-files@v1
        continue-on-error: true

      - name: Codeowner Verifier
        id: codeownerVerifier
        uses: garretpatten/codeowner-verifier@v1.1
        with:
          changedFiles: ${{ steps.diff.outputs.all }}
          directoryIgnoreList: '.git/ .sfdx/ .idea/ .vscode/ src/dependencies/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Finish and Output Time
        run: |
          echo "Codeowners Validator has completed."
          echo "Time: ${{ steps.codeownersValidator.outputs.timestamp }}"
