name: 'Example Workflow'

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Identify Changed Files
        id: diff
        uses: tj-actions/verify-changed-files@v10.1
        with:
          files: |
            *.js
            *.py
            *.ts
            *.txt
            *.yml

      - name: Codeowners Validator
        id: codeownersValidator
        uses: garretpatten/codeowners-validator@main
        with:
          changedFiles: ${{ steps.diff.outputs.changed_files }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Finish and Output Time
        run: |
          echo "Codeowners Validator has completed."
          echo "Time: ${{ steps.codeownersValidator.outputs.timestamp }}"