name: 'Example Workflow'

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  codeowners-validator-workflow:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Identify Changed Files
        id: diff
        uses: jitterbit/get-changed-files@v1

      - name: Codeowners Validator
        id: codeownersValidator
        uses: garretpatten/codeowners-validator@main
        with:
          changedFiles: ${{ steps.diff.outputs.all }}
          directoryIgnoreList: '.git/ .sfdx/ .idea/ .vscode/ src/dependencies/'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Finish and Output Time
        run: |
          echo "Codeowners Validator has completed."
          echo "Time: ${{ steps.codeownersValidator.outputs.timestamp }}"