name: Prettier

on: [pull_request, push]

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      # TODO: Pin at full length commit SHA
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
